name: airoll
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - appnope=0.1.3
  - asttokens=2.2.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.1.4
  - cpuonly=2.0
  - dataclasses=0.8
  - datasets=2.14.4
  - debugpy=1.6.8
  - decorator=5.1.1
  - dill=0.3.7
  - executing=1.2.0
  - filelock=3.12.2
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - huggingface_hub=0.16.4
  - humanfriendly=10.0
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - krb5=1.21.2
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.3
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libthrift=0.18.1
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuv=1.44.2
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nomkl=1.0
  - numpy=1.25.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - orc=1.9.0
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pygments=2.16.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.3.0
  - python_abi=3.9
  - pytorch=2.0.0
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.1.1
  - re2=2023.03.02
  - readline=8.2
  - regex=2023.8.8
  - requests=2.31.0
  - sacremoses=0.0.53
  - safetensors=0.3.2
  - setuptools=68.1.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sqlite=3.42.0
  - stack_data=0.6.2
  - sympy=1.12
  - tk=8.6.12
  - tokenizers=0.13.3
  - torchaudio=2.0.0
  - torchvision=0.14.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - transformers=4.31.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - wcwidth=0.2.6
  - wheel=0.41.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiofiles==23.2.1
      - altair==5.0.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - exceptiongroup==1.1.3
      - fastapi==0.101.1
      - ffmpy==0.3.1
      - fonttools==4.42.1
      - gradio==3.40.1
      - gradio-client==0.4.0
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - importlib-resources==6.0.1
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - linkify-it-py==2.0.2
      - markdown-it-py==2.2.0
      - matplotlib==3.7.2
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - orjson==3.9.5
      - pydantic==2.2.1
      - pydantic-core==2.6.1
      - pydub==0.25.1
      - pyparsing==3.0.9
      - python-multipart==0.0.6
      - referencing==0.30.2
      - rpds-py==0.9.2
      - semantic-version==2.10.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - toolz==0.12.0
      - torch-summary==1.4.5
      - uc-micro-py==1.0.2
      - uvicorn==0.23.2
      - websockets==11.0.3
